#!/usr/bin/env bash
# Materialize CRUST-bench subject(s) for CodeWeaver.
#
#   ./setup.sh cset [/path/to/CRUST-bench]
#   ./setup.sh --all [/path/to/CRUST-bench]
#
# LAYOUT PRODUCED, per subject:
#   subjects/<name>/pipeline/project/   the Rust working copy the agents may edit
#   subjects/<name>/c-source/           the original C project, READ ONLY reference
#   subjects/<name>/.oracle-master/     the held-out tests, never in the working copy
#
# THE ORACLE IS HELD OUT. CRUST ships its tests inside the project, at
# src/bin/*.rs, where `cargo test` picks them up automatically. If we left them
# in place the translator could read them, and every "test-blind" claim in the
# results would be false. So setup strips src/bin/ out of the working copy and
# keeps it in .oracle-master/, which tools/oracle.sh stages back at scoring time.
#
# Cargo.toml needs the same treatment: some subjects declare [[test]] targets
# pointing into src/bin/, and cargo errors out if those paths are missing. The
# working copy gets a stripped manifest; the original is kept beside the oracle.
set -eu

HERE="$(cd "$(dirname "$0")" && pwd)"
ALL_SUBJECTS="c-aces cset inversion_list lambda-calculus-eval"

ARG="${1:-}"
DATASET="${2:-$HOME/CRUST-bench}"
[ -n "$ARG" ] || { echo "usage: $0 <subject|--all> [CRUST-bench-root]" >&2; exit 2; }
case "$ARG" in
  --all) TARGETS="$ALL_SUBJECTS" ;;
  *) case " $ALL_SUBJECTS " in
       *" $ARG "*) TARGETS="$ARG" ;;
       *) echo "unknown subject '$ARG'. Available: $ALL_SUBJECTS" >&2; exit 2 ;;
     esac ;;
esac

[ -d "$DATASET/datasets/RBench" ] || { echo "CRUST-bench not found at $DATASET" >&2; exit 2; }

for PROJECT in $TARGETS; do
  # RBench directory names replace '-' with '_'; CBench keeps the original.
  RNAME="$(echo "$PROJECT" | tr '-' '_')"
  RSRC="$DATASET/datasets/RBench/$RNAME"
  CSRC="$DATASET/datasets/CBench/$PROJECT"
  [ -d "$RSRC" ] || { echo "missing RBench project: $RSRC" >&2; exit 2; }
  [ -d "$CSRC" ] || { echo "missing CBench project: $CSRC" >&2; exit 2; }

  SUBJECT="$HERE/subjects/$PROJECT"
  if [ -e "$SUBJECT" ]; then
    echo "[setup] $PROJECT already materialized; leaving it alone" >&2
    continue
  fi
  mkdir -p "$SUBJECT"

  WORK="$SUBJECT/pipeline/project"
  ORACLE="$SUBJECT/.oracle-master"
  mkdir -p "$WORK" "$ORACLE"

  cp -r "$RSRC/." "$WORK/"
  rm -rf "$WORK/target"

  # 1. Move the stub interfaces into src/, which is what lib.rs declares and what
  #    CRUST's own check_build.py does. This is the translator's canvas.
  if [ -d "$WORK/src/interfaces" ]; then
    mv "$WORK/src/interfaces"/*.rs "$WORK/src/" 2>/dev/null || true
    rmdir "$WORK/src/interfaces" 2>/dev/null || true
  fi

  # 2. Hold the tests out.
  if [ -d "$WORK/src/bin" ]; then
    mv "$WORK/src/bin" "$ORACLE/bin"
  fi
  cp "$WORK/Cargo.toml" "$ORACLE/Cargo.toml.oracle"

  # 3. Strip [[test]] blocks that point at the now-absent src/bin/.
  awk '
    /^\[\[test\]\]/ { skip=1; next }
    /^\[/           { skip=0 }
    !skip           { print }
  ' "$ORACLE/Cargo.toml.oracle" > "$WORK/Cargo.toml"

  # 4. The C project is the translation input. Read-only reference, no .git.
  #
  #    The C test directories are EXCLUDED. CRUST's Rust tests were generated by
  #    an LLM from exactly those C tests, so handing them to the translator would
  #    leak the oracle in another language and silently void every test-blind
  #    claim. This mirrors AlphaTrans, where src/test is likewise withheld.
  mkdir -p "$SUBJECT/c-source"
  ( cd "$CSRC" && tar -cf - \
      --exclude=.git --exclude=tests --exclude=test --exclude=t . ) \
    | ( cd "$SUBJECT/c-source" && tar -xf - )

  # 5. Freeze the pristine stub tree. Baseline runs rebuild from this, so a module
  #    the model never emits stays an unimplemented stub and fails honestly,
  #    rather than disappearing and breaking the build for unrelated reasons.
  mkdir -p "$SUBJECT/.scaffold"
  cp -r "$WORK/src" "$SUBJECT/.scaffold/src"
  cp "$WORK/Cargo.toml" "$SUBJECT/.scaffold/Cargo.toml"
  [ -f "$WORK/Cargo.lock" ] && cp "$WORK/Cargo.lock" "$SUBJECT/.scaffold/Cargo.lock"

  # 6. Config, generated from the template so every subject is configured identically.
  VALIDATE_CMD="bash ../../tools/oracle.sh --project $PROJECT --gate \"{gate}\""
  SLUG="$(echo "$PROJECT" | tr 'A-Z' 'a-z' | tr -c 'a-z0-9' '-' | sed 's/-*$//')"
  sed -e "s|__PROJECT__|$PROJECT|g" \
      -e "s|__PROJECT_SLUG__|$SLUG|g" \
      -e "s|__VALIDATE_CMD__|$VALIDATE_CMD|g" \
      "$HERE/codeweaver.template.toml" > "$SUBJECT/codeweaver.toml"

  # Test TARGET names are the gate vocabulary: one token per file in .oracle-master/bin.
  # Recorded so the scope stage can be checked against what the harness can actually
  # select, without anyone reading the tests themselves.
  ( cd "$ORACLE/bin" && ls *.rs 2>/dev/null | sed 's/\.rs$//' ) > "$SUBJECT/.gate-tokens.txt" || true

  # 5. Record the stub baseline: which tests pass with nothing implemented.
  #    Those are free points for every arm and must be visible in the results.
  cat > "$SUBJECT/.oracle-master/README.txt" <<EOF
Held-out oracle for $PROJECT.

bin/              the CRUST test targets, removed from the working copy
Cargo.toml.oracle the original manifest, including any [[test]] declarations

tools/oracle.sh stages these into a throwaway tree at scoring time. Nothing here
may be copied into pipeline/project, and no agent may read it.

PROVENANCE: these tests were generated by an LLM from the C sources against stub
interfaces (CRUST-bench). They are NOT human-verified, unlike the AlphaTrans
oracle. Treat the resulting scores accordingly.
EOF

  N_TESTS="$(grep -rc '#\[test\]' "$ORACLE/bin" 2>/dev/null | awk -F: '{s+=$2} END {print s+0}')"
  echo "[setup] $PROJECT: working copy at pipeline/project, $N_TESTS test fn(s) held out"
done
